public enum CelestialBodyType
{
    Star,
    GasGiant,
    RingedGasGiant,
    IceGiant,
    IcyPlanet,
    MoltenPlanet,
    ToxicPlanet,
    RockyPlanet,
    IcyMoon,
    RockyMoon,
    Asteroid,
    DefaultPlanet,
    Unknown,
    UnknownMajorBody,
    UnknownMinorBody,
    Pallyria,
    Earth,
    Luna
}