//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\programs\Godot\GloryOfRitiria\Parsers\StellarSystemParser\StellarGenerator.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace StellarSystemParser {

    using System.Globalization;
    using GloryOfRitiria.Scripts.Utils;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="StellarGeneratorParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IStellarGeneratorVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] StellarGeneratorParser.FileContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.stellar_system"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStellar_system([NotNull] StellarGeneratorParser.Stellar_systemContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.stellar_system_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStellar_system_body([NotNull] StellarGeneratorParser.Stellar_system_bodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.star"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar([NotNull] StellarGeneratorParser.StarContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.star_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_body([NotNull] StellarGeneratorParser.Star_bodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.celestial_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCelestial_body([NotNull] StellarGeneratorParser.Celestial_bodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.celestial_body_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCelestial_body_body([NotNull] StellarGeneratorParser.Celestial_body_bodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.satellites"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSatellites([NotNull] StellarGeneratorParser.SatellitesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.shipyards"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipyards([NotNull] StellarGeneratorParser.ShipyardsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.shipyard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipyard([NotNull] StellarGeneratorParser.ShipyardContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.shipyard_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShipyard_body([NotNull] StellarGeneratorParser.Shipyard_bodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.ships"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShips([NotNull] StellarGeneratorParser.ShipsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.ship"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShip([NotNull] StellarGeneratorParser.ShipContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.ship_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShip_body([NotNull] StellarGeneratorParser.Ship_bodyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.modules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModules([NotNull] StellarGeneratorParser.ModulesContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] StellarGeneratorParser.ModuleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] StellarGeneratorParser.NameContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.icon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIcon([NotNull] StellarGeneratorParser.IconContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.body_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_type([NotNull] StellarGeneratorParser.Body_typeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.ship_size"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShip_size([NotNull] StellarGeneratorParser.Ship_sizeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.distance_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDistance_from([NotNull] StellarGeneratorParser.Distance_fromContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.angle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAngle([NotNull] StellarGeneratorParser.AngleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.pull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPull([NotNull] StellarGeneratorParser.PullContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.body_distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_distance([NotNull] StellarGeneratorParser.Body_distanceContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.scientific_potential"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScientific_potential([NotNull] StellarGeneratorParser.Scientific_potentialContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.building_progress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBuilding_progress([NotNull] StellarGeneratorParser.Building_progressContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.star_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStar_class([NotNull] StellarGeneratorParser.Star_classContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.discovery_status"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDiscovery_status([NotNull] StellarGeneratorParser.Discovery_statusContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] StellarGeneratorParser.IdContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText([NotNull] StellarGeneratorParser.TextContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.inty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInty([NotNull] StellarGeneratorParser.IntyContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="StellarGeneratorParser.floaty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloaty([NotNull] StellarGeneratorParser.FloatyContext context);
}
} // namespace StellarSystemParser
