//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\programs\Godot\GloryOfRitiria\StellarSystemParser\StellarSystemParser\StellarGenerator.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace StellarSystemParser {

    using System.Globalization;

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="StellarGeneratorParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface IStellarGeneratorListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] StellarGeneratorParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] StellarGeneratorParser.FileContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.stellar_system"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStellar_system([NotNull] StellarGeneratorParser.Stellar_systemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.stellar_system"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStellar_system([NotNull] StellarGeneratorParser.Stellar_systemContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.stellar_system_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStellar_system_body([NotNull] StellarGeneratorParser.Stellar_system_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.stellar_system_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStellar_system_body([NotNull] StellarGeneratorParser.Stellar_system_bodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.star"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar([NotNull] StellarGeneratorParser.StarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.star"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar([NotNull] StellarGeneratorParser.StarContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.star_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_body([NotNull] StellarGeneratorParser.Star_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.star_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_body([NotNull] StellarGeneratorParser.Star_bodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.celestial_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCelestial_body([NotNull] StellarGeneratorParser.Celestial_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.celestial_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCelestial_body([NotNull] StellarGeneratorParser.Celestial_bodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.celestial_body_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCelestial_body_body([NotNull] StellarGeneratorParser.Celestial_body_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.celestial_body_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCelestial_body_body([NotNull] StellarGeneratorParser.Celestial_body_bodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.satellites"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSatellites([NotNull] StellarGeneratorParser.SatellitesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.satellites"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSatellites([NotNull] StellarGeneratorParser.SatellitesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.shipyards"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShipyards([NotNull] StellarGeneratorParser.ShipyardsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.shipyards"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShipyards([NotNull] StellarGeneratorParser.ShipyardsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.shipyard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShipyard([NotNull] StellarGeneratorParser.ShipyardContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.shipyard"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShipyard([NotNull] StellarGeneratorParser.ShipyardContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.shipyard_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShipyard_body([NotNull] StellarGeneratorParser.Shipyard_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.shipyard_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShipyard_body([NotNull] StellarGeneratorParser.Shipyard_bodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.ships"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShips([NotNull] StellarGeneratorParser.ShipsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.ships"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShips([NotNull] StellarGeneratorParser.ShipsContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.ship"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShip([NotNull] StellarGeneratorParser.ShipContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.ship"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShip([NotNull] StellarGeneratorParser.ShipContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.ship_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShip_body([NotNull] StellarGeneratorParser.Ship_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.ship_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShip_body([NotNull] StellarGeneratorParser.Ship_bodyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.modules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModules([NotNull] StellarGeneratorParser.ModulesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.modules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModules([NotNull] StellarGeneratorParser.ModulesContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] StellarGeneratorParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] StellarGeneratorParser.ModuleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] StellarGeneratorParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] StellarGeneratorParser.NameContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.icon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIcon([NotNull] StellarGeneratorParser.IconContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.icon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIcon([NotNull] StellarGeneratorParser.IconContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.distance_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDistance_from([NotNull] StellarGeneratorParser.Distance_fromContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.distance_from"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDistance_from([NotNull] StellarGeneratorParser.Distance_fromContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.angle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAngle([NotNull] StellarGeneratorParser.AngleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.angle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAngle([NotNull] StellarGeneratorParser.AngleContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.pull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPull([NotNull] StellarGeneratorParser.PullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.pull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPull([NotNull] StellarGeneratorParser.PullContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.body_distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody_distance([NotNull] StellarGeneratorParser.Body_distanceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.body_distance"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody_distance([NotNull] StellarGeneratorParser.Body_distanceContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.building_progress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBuilding_progress([NotNull] StellarGeneratorParser.Building_progressContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.building_progress"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBuilding_progress([NotNull] StellarGeneratorParser.Building_progressContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.star_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStar_class([NotNull] StellarGeneratorParser.Star_classContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.star_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStar_class([NotNull] StellarGeneratorParser.Star_classContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.discovery_status"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiscovery_status([NotNull] StellarGeneratorParser.Discovery_statusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.discovery_status"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiscovery_status([NotNull] StellarGeneratorParser.Discovery_statusContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterId([NotNull] StellarGeneratorParser.IdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitId([NotNull] StellarGeneratorParser.IdContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.inty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInty([NotNull] StellarGeneratorParser.IntyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.inty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInty([NotNull] StellarGeneratorParser.IntyContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.floaty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloaty([NotNull] StellarGeneratorParser.FloatyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.floaty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloaty([NotNull] StellarGeneratorParser.FloatyContext context);
}
} // namespace StellarSystemParser
