//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:\programs\Godot\GloryOfRitiria\Parsers\StellarSystemParser\StellarGenerator.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace StellarSystemParser {

    using System.Globalization;
    using GloryOfRitiria.Scripts.Utils.StellarParser;


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IStellarGeneratorListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class StellarGeneratorBaseListener : IStellarGeneratorListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] StellarGeneratorParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] StellarGeneratorParser.FileContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.stellar_system"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStellar_system([NotNull] StellarGeneratorParser.Stellar_systemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.stellar_system"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStellar_system([NotNull] StellarGeneratorParser.Stellar_systemContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.stellar_system_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStellar_system_body([NotNull] StellarGeneratorParser.Stellar_system_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.stellar_system_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStellar_system_body([NotNull] StellarGeneratorParser.Stellar_system_bodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.star"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar([NotNull] StellarGeneratorParser.StarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.star"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar([NotNull] StellarGeneratorParser.StarContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.star_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar_body([NotNull] StellarGeneratorParser.Star_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.star_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar_body([NotNull] StellarGeneratorParser.Star_bodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.celestial_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCelestial_body([NotNull] StellarGeneratorParser.Celestial_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.celestial_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCelestial_body([NotNull] StellarGeneratorParser.Celestial_bodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.celestial_body_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCelestial_body_body([NotNull] StellarGeneratorParser.Celestial_body_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.celestial_body_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCelestial_body_body([NotNull] StellarGeneratorParser.Celestial_body_bodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.satellites"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSatellites([NotNull] StellarGeneratorParser.SatellitesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.satellites"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSatellites([NotNull] StellarGeneratorParser.SatellitesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.shipyards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShipyards([NotNull] StellarGeneratorParser.ShipyardsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.shipyards"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShipyards([NotNull] StellarGeneratorParser.ShipyardsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.shipyard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShipyard([NotNull] StellarGeneratorParser.ShipyardContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.shipyard"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShipyard([NotNull] StellarGeneratorParser.ShipyardContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.shipyard_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShipyard_body([NotNull] StellarGeneratorParser.Shipyard_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.shipyard_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShipyard_body([NotNull] StellarGeneratorParser.Shipyard_bodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.ships"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShips([NotNull] StellarGeneratorParser.ShipsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.ships"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShips([NotNull] StellarGeneratorParser.ShipsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.ship"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShip([NotNull] StellarGeneratorParser.ShipContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.ship"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShip([NotNull] StellarGeneratorParser.ShipContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.ship_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShip_body([NotNull] StellarGeneratorParser.Ship_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.ship_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShip_body([NotNull] StellarGeneratorParser.Ship_bodyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.modules"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModules([NotNull] StellarGeneratorParser.ModulesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.modules"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModules([NotNull] StellarGeneratorParser.ModulesContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModule([NotNull] StellarGeneratorParser.ModuleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.module"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModule([NotNull] StellarGeneratorParser.ModuleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterName([NotNull] StellarGeneratorParser.NameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitName([NotNull] StellarGeneratorParser.NameContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.icon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIcon([NotNull] StellarGeneratorParser.IconContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.icon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIcon([NotNull] StellarGeneratorParser.IconContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.body_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody_type([NotNull] StellarGeneratorParser.Body_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.body_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody_type([NotNull] StellarGeneratorParser.Body_typeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.ship_size"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShip_size([NotNull] StellarGeneratorParser.Ship_sizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.ship_size"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShip_size([NotNull] StellarGeneratorParser.Ship_sizeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.distance_from"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDistance_from([NotNull] StellarGeneratorParser.Distance_fromContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.distance_from"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDistance_from([NotNull] StellarGeneratorParser.Distance_fromContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.angle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAngle([NotNull] StellarGeneratorParser.AngleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.angle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAngle([NotNull] StellarGeneratorParser.AngleContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.pull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPull([NotNull] StellarGeneratorParser.PullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.pull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPull([NotNull] StellarGeneratorParser.PullContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.body_distance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody_distance([NotNull] StellarGeneratorParser.Body_distanceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.body_distance"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody_distance([NotNull] StellarGeneratorParser.Body_distanceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.scientific_potential"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScientific_potential([NotNull] StellarGeneratorParser.Scientific_potentialContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.scientific_potential"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScientific_potential([NotNull] StellarGeneratorParser.Scientific_potentialContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.building_progress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuilding_progress([NotNull] StellarGeneratorParser.Building_progressContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.building_progress"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuilding_progress([NotNull] StellarGeneratorParser.Building_progressContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.star_class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStar_class([NotNull] StellarGeneratorParser.Star_classContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.star_class"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStar_class([NotNull] StellarGeneratorParser.Star_classContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.discovery_status"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiscovery_status([NotNull] StellarGeneratorParser.Discovery_statusContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.discovery_status"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiscovery_status([NotNull] StellarGeneratorParser.Discovery_statusContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterId([NotNull] StellarGeneratorParser.IdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitId([NotNull] StellarGeneratorParser.IdContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] StellarGeneratorParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] StellarGeneratorParser.TextContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.inty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInty([NotNull] StellarGeneratorParser.IntyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.inty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInty([NotNull] StellarGeneratorParser.IntyContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="StellarGeneratorParser.floaty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloaty([NotNull] StellarGeneratorParser.FloatyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="StellarGeneratorParser.floaty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloaty([NotNull] StellarGeneratorParser.FloatyContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace StellarSystemParser
