namespace GloryOfRitiria.Scripts.Utils;

public enum StellarGeneratorPoint
{
    INITMAP, INITSYSTEM, SETSYSTEMNAME, ADDSYSTEM, ADDSTAR, INITSTAR, SETSTARNAME, ADDBODYTOSTAR, ADDTOSHIPYARD, 
    INITBODY, SETBODYNAME, SETBODYICON, ADDSHIPYARD, SETISSATELLITE, ADDSATELLITETOPARENT,
    SETISNTSATELLITE, INITSHIPYARD, SETSHIPYARDBUSY, ADDSHIP,
    INITSHIP, SETSHIPYARDBUILDINGPROGRESS, ADDMODULE, INITMODULE, SETMODULEDURABILITY, SETSYSTEMDISTANCE,
    SETSYSTEMANGLE, SETSYSTEMPULL, SETBODYDISTANCE, SETSTARCLASSOD, SETSTARCLASSRD, SETSTARCLASSYD, SETSTATUSEXPLORED,
    SETSTATUSKNOWN, SETSTATUSUNDISCOVERED, ERRORVERIFICATION
}